### ISSUE TITLE
where clause support operator "like" ？

### ISSUE THREAD

**Issue by wulin76** [zussel/matador#109]
I write my sql with operator 'like' in where clause, and how could i   migrate it into matador？

**Comment by zussel** [comment]
That's nice, I appreciate that you try to contribute to matador! Just create a branch and a pull request.

There are several steps to do, to get the 'like' command done:

- You have to add a token in `include/matador/sql/token.hpp`
- I would 'like' implement as the the `in` clause in `include/matador/sql/condition.hpp` (line 543), with two parameters, condition and string.
- Extend the condition operands in `src/sql/condition.cpp`
 Than one could write code `.where(matador::like("name"_col, "%abcd%")`. Or maybe you find a more intuitive way.
- Test 'like' in `test/sql/ConditionUnitTest.hpp`
- To test it with all database backends write a test in `test/sql/QueryTestUnit.hpp`
- Create a pull request, so all tests will be execute by github, I can review the code and help to answer your questions.

**Comment by wulin76** [comment]
i would try

**Comment by zussel** [comment]
fixed with #114
