### ISSUE TITLE
mysql 8: my_bool type removed 

### ISSUE THREAD

**Issue by suisou** [zussel/matador#110]
as the title,
please fix it.

**Comment by zussel** [comment]
Thanks for the hint! I'll fix this in one of the next releases.

[Removed my_bool type in MySQL release notes](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling)

**Comment by zussel** [comment]
Fixed with #113
