### ISSUE TITLE
two std::string fields can't  store to mysql! 

### ISSUE THREAD

**Issue by suisou** [zussel/matador#111]
base on the demo code. add the filed "ip" .
  
 **std::string ip;**
 template < class SERIALIZER >
    void serialize(SERIALIZER& serializer) {
        serializer.serialize("id", id);
        serializer.serialize("name", name, 255);
        **serializer.serialize("ip", ip);**
if I add a string field to  serialize function, compile & link normal, but error mesg showed when running:
what():  mysql: Column 'id' cannot be null (INSERT INTO `person` (`id`, `name`, `ip`, `age`) VALUES (?, ?, ?, ?) )

**Comment by zussel** [comment]
I tried to reproduce this issue, but without success (see my code [here](https://gist.github.com/zussel/3e88295be7f71588f7a431730bd2c0db)). This code is also available in current develop branch in `OrmTestUnit::test_demo`.

Could you provide me your code and tell me which version of matador you're using? Thanks in advance!

**Comment by zussel** [comment]
Btw you can enable a simple stdout SQL log by calling `enable_log()` on either an instance of class `persistence` or an instance of class `connection`.

**Comment by suisou** [comment]
the code from matador-master,     2019-12-13 13:44:52
i modiyf it  for mysql 8:  my_bool to bool.


this is the demo code . 
[main.zip](https://github.com/zussel/matador/files/3999235/main.zip)
the logs:
[suisou@localhost projects]$ ./Matador_Mysql.out
SQL: CREATE TABLE `person` (`id` BIGINT NOT NULL PRIMARY KEY, `name` VARCHAR(255), `age` INTEGER UNSIGNED)
SQL: CREATE TABLE `person_color` (`person_id` BIGINT, `color` VARCHAR(255))
SQL: START TRANSACTION
SQL: INSERT INTO `person` (`id`, `name`, `age`) VALUES (?, ?, ?)
SQL: COMMIT
SQL: START TRANSACTION
SQL: UPDATE `person` SET `id`=?, `name`=?, `age`=? WHERE `id` = ?
SQL: INSERT INTO `person_color` (`person_id`, `color`) VALUES (?, ?)
SQL: INSERT INTO `person_color` (`person_id`, `color`) VALUES (?, ?)
SQL: COMMIT
[suisou@localhost projects]$

line 39 & 66  commented. work normally.


but decomment the two lines .
the logs:
[suisou@localhost projects]$ ./Matador_Mysql.out
SQL: CREATE TABLE `person` (`id` BIGINT NOT NULL PRIMARY KEY, `name` VARCHAR(255                               ), `tname` VARCHAR(255), `age` INTEGER UNSIGNED)
SQL: CREATE TABLE `person_color` (`person_id` BIGINT, `color` VARCHAR(255))
SQL: START TRANSACTION
SQL: INSERT INTO `person` (`id`, `name`, `tname`, `age`) VALUES (?, ?, ?, ?)
terminate called after throwing an instance of 'matador::mysql::mysql_stmt_excep                               tion'
  what():  mysql: Column 'id' cannot be null (INSERT INTO `person` (`id`, `name`                               , `tname`, `age`) VALUES (?, ?, ?, ?) )
Aborted (core dumped)
[suisou@localhost projects]$

**Comment by suisou** [comment]
in centos 8 stream with gcc

**Comment by suisou** [comment]
please see the pull request I submited.

**Comment by zussel** [comment]
Thanks for your pull request. I'll take a look into it and tyr to fix the problem. I'll also provide a switch to toggle between `my_bool` and `bool` for mysql. Then the test in the PR will again be green.

**Comment by zussel** [comment]
Fixed with #113
