### ISSUE TITLE
mysql 8  res.empty() no rows in table ,but return false

### ISSUE THREAD

**Issue by suisou** [zussel/matador#118]
auto res = q
        .select()
        .where(id == 0)
        .execute(conn);
no rows in the table.

but     res.empty()   return false.

**Comment by suisou** [comment]
replace empty() with size()==0

**Comment by zussel** [comment]
That's right! Thanks for the hint. I'll fix this in the next release.

**Comment by zussel** [comment]
Fixed with commit e12c82a31aae9b3800e8ccf501e2dc6bd9c58a46.
