### ISSUE TITLE
how to insert blob type data

### ISSUE THREAD

**Issue by china-zhangjun** [zussel/matador#123]

**Comment by zussel** [comment]
I'm sorry by now _matador_ isn't able to store blob data. I've addressed this already in issue #18 but didn't find time to implement it.

It'll be part of _matador_ before version 1.0.0.

**Comment by china-zhangjun** [comment]
thanks for your reply.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Sascha&amp;nbsp;Kühl&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月2日(星期四) 晚上7:35
收件人:&nbsp;&quot;zussel/matador&quot;<matador@noreply.github.com&gt;;
抄送:&nbsp;&quot;china-zhangjun&quot;<460310239@QQ.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zussel/matador] how to insert blob type data (#123)
