### ISSUE TITLE
Raise exception if a specific column value is null (mysql  query)

### ISSUE THREAD

**Issue by lgztx96** [zussel/matador#156]
![Snipaste_2024-01-09_02-15-22](https://github.com/zussel/matador/assets/29275743/a4ca90d6-f177-41f5-9be0-69f0f3d231ae)

![Snipaste_2024-01-09_01-16-25](https://github.com/zussel/matador/assets/29275743/56222aac-e47a-44bc-aacf-0c4dabab19de)

![Snipaste_2024-01-09_01-15-51](https://github.com/zussel/matador/assets/29275743/e32c639f-dc3b-436d-a0f4-e47df9b1d856)
![Snipaste_2024-01-09_02-14-18](https://github.com/zussel/matador/assets/29275743/15d01722-42a8-42c3-9311-24756106306f)

![Snipaste_2024-01-09_02-14-53](https://github.com/zussel/matador/assets/29275743/9aff24ad-ef22-4563-a7a2-bc6c1c01b581)

**Comment by zussel** [comment]
Thanks for the issue . That's indeed untested code. Will be fixed soon.

**Comment by zussel** [comment]
It is checked that the retrieved value is valid and not null before set into variable. This was also the issue for mssql. A test was also added.

**Comment by lgztx96** [comment]
> 在设置到变量之前，检查检索到的值是否有效且不为 null。这也是mssql的问题。还添加了一个测试。

issue not fully fixed in version 9.1.0
for example:
![Snipaste_2024-01-12_19-48-05](https://github.com/zussel/matador/assets/29275743/f9e3cf15-3ecd-4ff2-bc81-0c0a2c82ae7f)

https://github.com/zussel/matador/blob/0c5d8f793fc8554b96b026a6c72e1be5ccffa1e5/src/db/mysql/mysql_prepared_result.cpp#L260
if  column is null,  length is equal to the previous value of column

**Comment by zussel** [comment]
The "is null" check was added for all database backends (postgres, mysql, sqlite and mssql). Beside for strings also for date and time a special handling had to be added.
