### ISSUE TITLE
Fixed Some Bugs for Sqlite

### ISSUE THREAD

**Issue by lld1995** [zussel/matador#91]
https://blog.csdn.net/nightwizard2030/article/details/87812502

From the blog post above I extracted the followwing issues:

- [x] Introduce int64/unit64
- [x] Fix modification of identifiers
- [x] Handle return types when executing SQLite queries
- [x] Add a fillin of make_unique to be c++11 conform

**Comment by zussel** [comment]
Hi,

thank you for your nice feedback! I had to translate it with google translate but I think I got your message right.

As for c++11/14 I see that `make_unique()` is indeed the only call used from c++14. I'm thinking about to provide an own implemenation of ´make_unique()´ and drop the need for c++14.

As for your suggestions for the sqlite backend you can provide a pull request based on branch develop. If you don't have modified source code, I'll try to fix it.
I appreciate any suggestion or comment on any of the backends!

**Comment by lld1995** [comment]
and i have a problem that how to change identifier by this?

**Comment by lld1995** [comment]
and i have a problem that how to change identifier's value by this? when i changed the value,it can't edit value in datebase.

**Comment by lld1995** [comment]
and i have a problem that how to change identifier's value by this? when i changed the value,it can't edit value in datebase,now i solved it by query statment  ( persist->conn->query )

**Comment by zussel** [comment]
Sorry, but I think, I haven't understand your issue completely.

You want to change identifiers value on database? Or if you change identifiers value it is not written to database?
Maybe write some code with comments in your answer.
